/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ScamType = IDL.Variant({
  'romanceScam' : IDL.Null,
  'investmentFraud' : IDL.Null,
  'other' : IDL.Text,
  'phishing' : IDL.Null,
  'identityTheft' : IDL.Null,
});
export const Time = IDL.Int;
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'scamType' : ScamType,
  'timestamp' : Time,
  'reporter' : IDL.Principal,
});
export const ScamTypeCount = IDL.Record({
  'count' : IDL.Nat,
  'scamType' : ScamType,
});
export const Stats = IDL.Record({
  'mostCommonScamType' : IDL.Opt(ScamTypeCount),
  'totalReports' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getReportsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Report)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getTotalReports' : IDL.Func([], [IDL.Nat], ['query']),
  'submitReport' : IDL.Func([IDL.Text, ScamType], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ScamType = IDL.Variant({
    'romanceScam' : IDL.Null,
    'investmentFraud' : IDL.Null,
    'other' : IDL.Text,
    'phishing' : IDL.Null,
    'identityTheft' : IDL.Null,
  });
  const Time = IDL.Int;
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'scamType' : ScamType,
    'timestamp' : Time,
    'reporter' : IDL.Principal,
  });
  const ScamTypeCount = IDL.Record({
    'count' : IDL.Nat,
    'scamType' : ScamType,
  });
  const Stats = IDL.Record({
    'mostCommonScamType' : IDL.Opt(ScamTypeCount),
    'totalReports' : IDL.Nat,
  });
  
  return IDL.Service({
    'getReportsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Report)],
        ['query'],
      ),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getTotalReports' : IDL.Func([], [IDL.Nat], ['query']),
    'submitReport' : IDL.Func([IDL.Text, ScamType], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };