/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Report {
  'id' : bigint,
  'description' : string,
  'scamType' : ScamType,
  'timestamp' : Time,
  'reporter' : Principal,
}
export type ScamType = { 'romanceScam' : null } |
  { 'investmentFraud' : null } |
  { 'other' : string } |
  { 'phishing' : null } |
  { 'identityTheft' : null };
export interface ScamTypeCount { 'count' : bigint, 'scamType' : ScamType }
export interface Stats {
  'mostCommonScamType' : [] | [ScamTypeCount],
  'totalReports' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'getReportsByUser' : ActorMethod<[Principal], Array<Report>>,
  'getStats' : ActorMethod<[], Stats>,
  'getTotalReports' : ActorMethod<[], bigint>,
  'submitReport' : ActorMethod<[string, ScamType], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];