/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Stats {
    mostCommonScamType?: ScamTypeCount;
    totalReports: bigint;
}
export interface ScamTypeCount {
    count: bigint;
    scamType: ScamType;
}
export type Time = bigint;
export interface Report {
    id: bigint;
    description: string;
    scamType: ScamType;
    timestamp: Time;
    reporter: Principal;
}
export type ScamType = {
    __kind__: "romanceScam";
    romanceScam: null;
} | {
    __kind__: "investmentFraud";
    investmentFraud: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "phishing";
    phishing: null;
} | {
    __kind__: "identityTheft";
    identityTheft: null;
};
export interface backendInterface {
    getReportsByUser(user: Principal): Promise<Array<Report>>;
    getStats(): Promise<Stats>;
    getTotalReports(): Promise<bigint>;
    submitReport(description: string, scamType: ScamType): Promise<bigint>;
}
import type { Report as _Report, ScamType as _ScamType, ScamTypeCount as _ScamTypeCount, Stats as _Stats, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getReportsByUser(arg0: Principal): Promise<Array<Report>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReportsByUser(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReportsByUser(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<Stats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return from_candid_Stats_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return from_candid_Stats_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalReports(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalReports();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalReports();
            return result;
        }
    }
    async submitReport(arg0: string, arg1: ScamType): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReport(arg0, to_candid_ScamType_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReport(arg0, to_candid_ScamType_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_Report_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ScamTypeCount_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScamTypeCount): ScamTypeCount {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_ScamType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScamType): ScamType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Stats_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stats): Stats {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ScamTypeCount]): ScamTypeCount | null {
    return value.length === 0 ? null : from_candid_ScamTypeCount_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    count: bigint;
    scamType: _ScamType;
}): {
    count: bigint;
    scamType: ScamType;
} {
    return {
        count: value.count,
        scamType: from_candid_ScamType_n4(_uploadFile, _downloadFile, value.scamType)
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    description: string;
    scamType: _ScamType;
    timestamp: _Time;
    reporter: Principal;
}): {
    id: bigint;
    description: string;
    scamType: ScamType;
    timestamp: Time;
    reporter: Principal;
} {
    return {
        id: value.id,
        description: value.description,
        scamType: from_candid_ScamType_n4(_uploadFile, _downloadFile, value.scamType),
        timestamp: value.timestamp,
        reporter: value.reporter
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mostCommonScamType: [] | [_ScamTypeCount];
    totalReports: bigint;
}): {
    mostCommonScamType?: ScamTypeCount;
    totalReports: bigint;
} {
    return {
        mostCommonScamType: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.mostCommonScamType)),
        totalReports: value.totalReports
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    romanceScam: null;
} | {
    investmentFraud: null;
} | {
    other: string;
} | {
    phishing: null;
} | {
    identityTheft: null;
}): {
    __kind__: "romanceScam";
    romanceScam: null;
} | {
    __kind__: "investmentFraud";
    investmentFraud: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "phishing";
    phishing: null;
} | {
    __kind__: "identityTheft";
    identityTheft: null;
} {
    return "romanceScam" in value ? {
        __kind__: "romanceScam",
        romanceScam: value.romanceScam
    } : "investmentFraud" in value ? {
        __kind__: "investmentFraud",
        investmentFraud: value.investmentFraud
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "phishing" in value ? {
        __kind__: "phishing",
        phishing: value.phishing
    } : "identityTheft" in value ? {
        __kind__: "identityTheft",
        identityTheft: value.identityTheft
    } : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Report>): Array<Report> {
    return value.map((x)=>from_candid_Report_n2(_uploadFile, _downloadFile, x));
}
function to_candid_ScamType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScamType): _ScamType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "romanceScam";
    romanceScam: null;
} | {
    __kind__: "investmentFraud";
    investmentFraud: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "phishing";
    phishing: null;
} | {
    __kind__: "identityTheft";
    identityTheft: null;
}): {
    romanceScam: null;
} | {
    investmentFraud: null;
} | {
    other: string;
} | {
    phishing: null;
} | {
    identityTheft: null;
} {
    return value.__kind__ === "romanceScam" ? {
        romanceScam: value.romanceScam
    } : value.__kind__ === "investmentFraud" ? {
        investmentFraud: value.investmentFraud
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "phishing" ? {
        phishing: value.phishing
    } : value.__kind__ === "identityTheft" ? {
        identityTheft: value.identityTheft
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
